services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      - MYSQL_USER=
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=
      - MYSQL_ROOT_PASSWORD=
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: